omikuji/urls.py
from django.urls import path
from . import views

app_name = 'omikuji'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include   # includeをimport

urlpatterns = [
    path('omikuji/', include('omikuji.urls')),    # omikuji/でアクセスした際はomikujiのURL設定を参照させる
    path('admin/', admin.site.urls),
]

omikuji/models.py
from django.db import models

# Create your models here.

omikuji/views.py
from django.shortcuts import render
import random   # randomをインポート


# Create your views here.
def index(request):
    return render(request, 'omikuji/index.html')


def result(request):
    l = ('大吉', '中吉', '小吉', '凶', '大凶')
    fortun = random.choice(l)
    # 運勢の情報を格納
    context = {
        'omikuji': fortun
    }
    return render(request, 'omikuji/result.html', context)  # contextの情報をテンプレートに送る

omikuji/templates/omikuji/base.html
{% load static %}   <!-- 静的ファイルを使えるための記述 -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Djangoでおみくじアプリを作ろう</title>
    <link href="{% static 'omikuji/css/style.css' %}" rel="stylesheet">     <!-- CSSの読み込み設定を追加 -->
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

omikuji/templates/omikuji/index.html
{% extends 'omikuji/base.html' %}
{% load static %}   <!-- 静的ファイルを使えるための記述 -->

{% block content %}
    <h1>Djangoで作るおみくじアプリ</h1>
    <p>今日の運勢を占います</p>
    <div><img src="{% static 'omikuji/img/omikuji.png' %}" alt="おみくじ"></div>    <!-- イメージ画像のリンクを追加 -->
    <div><a href="{% url 'omikuji:result' %}">おみくじを引く</a></div>  <!-- result.htmlへの画面遷移を追加 -->
{% endblock %}

omikuji/templates/omikuji/result.html
{% extends 'omikuji/base.html' %}

{% block content %}
    <h1>今日の運勢は</h1>
    <p><strong>{{ omikuji }}</strong></p>
    <div><a href="{% url 'omikuji:index' %}">トップページに戻る</a></div>   <!-- index.htmlへの画面遷移を追加 -->
{% endblock %}